/**
 * The FibonacciSpiral program implements an application that
 * animates Fibonacci Spiral.
 *
 * @author  Piotr Czapnik, Karol Urban
 * @version 1.0
 */
package libapp;

import java.awt.BorderLayout;
import javax.swing.JPanel;

public class Main extends javax.swing.JFrame {

    String[] message = {"Blad danych - powinno byc np. 1",
        "Ilość spiral powinna być l. naturalną",
        "Wszystkie dane powinny > 0.0"};

    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        spiral = new javax.swing.JTextField();
        rysuj = new javax.swing.JButton();
        czysc = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        delay = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        net = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        note01 = new javax.swing.JLabel();
        note02 = new javax.swing.JLabel();
        note03 = new javax.swing.JLabel();
        drawPanel = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setLabelFor(spiral);
        jLabel1.setText("Długość spirali:");
        jLabel1.setToolTipText("");

        spiral.setColumns(5);
        spiral.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        spiral.setText("1");
        spiral.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                spiralKeyTyped(evt);
            }
        });

        rysuj.setText("rysuj");
        rysuj.setMaximumSize(new java.awt.Dimension(84, 35));
        rysuj.setMinimumSize(new java.awt.Dimension(84, 35));
        rysuj.setPreferredSize(new java.awt.Dimension(84, 35));
        rysuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rysujActionPerformed(evt);
            }
        });

        czysc.setText("czysc");
        czysc.setMaximumSize(new java.awt.Dimension(85, 35));
        czysc.setMinimumSize(new java.awt.Dimension(85, 35));
        czysc.setPreferredSize(new java.awt.Dimension(85, 35));
        czysc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                czyscActionPerformed(evt);
            }
        });

        jLabel9.setLabelFor(delay);
        jLabel9.setText("Opoznienie:");

        delay.setColumns(5);
        delay.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        delay.setText("1");
        delay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                delayKeyTyped(evt);
            }
        });

        jLabel10.setText("s");

        net.setLabelFor(jCheckBox1);
        net.setText("Siatka:");

        jCheckBox1.setSelected(true);

        note01.setForeground(new java.awt.Color(255, 0, 0));
        note01.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        note01.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        note02.setForeground(new java.awt.Color(255, 0, 0));
        note02.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        note02.setToolTipText("");
        note02.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        note03.setForeground(new java.awt.Color(255, 0, 0));
        note03.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        note03.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spiral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(note01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(net, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(5, 5, 5)))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(delay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jCheckBox1)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(note02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(note03, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rysuj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(czysc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spiral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(delay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(net)
                    .addComponent(jCheckBox1))
                .addGap(18, 18, 18)
                .addComponent(note01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(note02)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(note03)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rysuj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(czysc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("");
        spiral.getAccessibleContext().setAccessibleName("");
        jLabel9.getAccessibleContext().setAccessibleName("");
        delay.getAccessibleContext().setAccessibleName("");
        net.getAccessibleContext().setAccessibleName("");

        drawPanel.setBackground(new java.awt.Color(255, 255, 255));
        drawPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        drawPanel.setPreferredSize(new java.awt.Dimension(993, 616));

        javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
        drawPanel.setLayout(drawPanelLayout);
        drawPanelLayout.setHorizontalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 974, Short.MAX_VALUE)
        );
        drawPanelLayout.setVerticalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(drawPanel, 980, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(drawPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_delayKeyTyped
        if (delay.getText().length() >= 3) {
            evt.consume();
        }
    }//GEN-LAST:event_delayKeyTyped

    private void czyscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_czyscActionPerformed
        Dane.setDefault();
        Dane.delay = 0;
        Dane.spiraltmp = 0;
        Dane.spiralnum = 0;
        drawPanel.removeAll();
        drawPanel.validate();
        drawPanel.repaint();
        spiral.setText("1");
        delay.setText("1");
        note01.setText("");
        note02.setText("");
        note03.setText("");
    }//GEN-LAST:event_czyscActionPerformed

    private void rysujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rysujActionPerformed
        note01.setText("");
        note02.setText("");
        note03.setText("");
        try {
            Dane.spiraltmp = Double.parseDouble(spiral.getText().replace(',', '.'));
            Dane.net = jCheckBox1.isSelected();

            if (Dane.spiraltmp != (int) Dane.spiraltmp) {
                note01.setText(message[1]);
                note02.setText("Program wykonano dla: " + ((int) Math.round(Dane.spiraltmp)));
                note03.setText("czyli najbliższej liczby naturalnej.");
                spiral.setText(Integer.toString((int) Math.round(Dane.spiraltmp)));
            }

            Dane.spiralnum = (int) Math.round(Dane.spiraltmp);

            if (Dane.spiralnum > 16) {
                spiral.setText("16");
                Dane.spiralnum = 16;
                note01.setText("Program został wykonany dla n=16,");
                note02.setText("gdyż jest to maksymalna zauważalna");
                note03.setText("liczba dla danej rozdzielczości.");
            }

            if (Dane.spiralnum <= 0) {
                throw new NumberFormatException();
            }

            Dane.delay = Double.parseDouble(delay.getText().replace(',', '.'));

            if (Dane.delay < 0) {
                throw new NumberFormatException();
            }
            if (Dane.f == false) {
                Dane.setDefault();
                drawPanel.removeAll();
                drawPanel.validate();
                drawPanel.repaint();
                drawPanel.setLayout(new BorderLayout());
                JPanel panel = new DrawPanel();
                drawPanel.add(panel);
                drawPanel.validate();
            } else {
                note02.setText("Animacja została przerwana.");
                Dane.g = true;
            }
        } catch (NumberFormatException e) {
            note01.setText(message[0]);
            note02.setText(message[2]);
            if (Dane.spiralnum <= 0) {
                note03.setText(message[1]);
            }
        } catch (NullPointerException e) {
            note01.setText(message[0]);
            note02.setText(message[2]);
        }
    }//GEN-LAST:event_rysujActionPerformed

    private void spiralKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spiralKeyTyped
        if (spiral.getText().length() >= 3) {
            evt.consume();
        }
    }//GEN-LAST:event_spiralKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton czysc;
    private javax.swing.JTextField delay;
    private javax.swing.JPanel drawPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel net;
    private javax.swing.JLabel note01;
    private javax.swing.JLabel note02;
    private javax.swing.JLabel note03;
    private javax.swing.JButton rysuj;
    private javax.swing.JTextField spiral;
    // End of variables declaration//GEN-END:variables

    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Main m = new Main();
                m.setVisible(true);
            }
        });
    }

}
